### ISSUE TITLE
Kibana version 7.x fails to start

### ISSUE THREAD

**Issue by Krish2106** [geerlingguy/ansible-role-kibana#38]
Kibana 7.x fails to start with  "FATAL Error: [elasticsearch.url]: definition for this key is missing"
As part of breaking changes on Kibana 7.x elasticsearch.url is deprecated and elasticsearch.hosts is used instead.
https://github.com/geerlingguy/ansible-role-kibana/blob/master/templates/kibana.yml.j2#L28

**Comment by kalemontes** [comment]
I also struggle with this...

You can over come this by setting the `kibana_config_template` variable to reference your own template file as follow :

```yaml
- name: "Install and configures Kibana"
  import_role:
    name: geerlingguy.kibana
  vars:
    kibana_version: 7.x
    kibana_config_template: "mytemplate.j2"
```

The content of `mytemplate.j2` can be the official lastest https://github.com/elastic/kibana/blob/master/config/kibana.yml where you modify the following template variable as follow :

```yaml
server.port: {{ kibana_server_port }}
server.host: "{{ kibana_server_host }}"
elasticsearch.hosts: {{ kibana_elasticsearch_url|to_json }}
{% if kibana_elasticsearch_username and kibana_elasticsearch_password %}
elasticsearch.username: "{{ kibana_elasticsearch_username }}"
elasticsearch.password: "{{ kibana_elasticsearch_password }}"
{% else %}
#elasticsearch.username: "user"
#elasticsearch.password: "pass"
{% endif %}
{% endif %}
```
