### ISSUE TITLE
Update to Kibana 4

### ISSUE THREAD

**Issue by ebuildy** [geerlingguy/ansible-role-kibana#4]
Just to know if an update to Kibana 4 is planed ?

Thanks,

**Comment by geerlingguy** [comment]
Yes... and it looks like @frodopwns might be working on it a little too... I haven't touched my prod ELK instances for a few months now, so I'll have to come back in and see what needs to be changed to support 4.x (hopefully nothing/not much!).

**Comment by frodopwns** [comment]
Kibana 4 is quite a bit different from Kibana 3 in terms of UI and how dashboards are created.  It may be a bit jarring for anyone currently using 3.x.

**Comment by frodopwns** [comment]
Also I believe they switched to a NodeJS backed so serving the app will be a bit different as well.

**Comment by johnjelinek** [comment]
Any updates on this?

**Comment by geerlingguy** [comment]
This is the next role I'm running through in my 'semiannual role cleanup' run, so I'm hoping to get to this in the next few days/week.

**Comment by johnjelinek** [comment]
@geerlingguy: I've had some success with this [playbook](https://github.com/mrlesmithjr/ansible-elk-kibana), maybe you can use it as a reference.

**Comment by esnellman** [comment]
Hi All,

First time user trying to follow the book.  Spent much time which seems common on the CN for the certificates..

My forwarder:
/var/log/syslog reporting 
Read error looking for ack: read tcp 212.47.251.101:5000: i/o timeout

My ELK machine:
/var/log/logstash reporting
[logstash-0.0.0.0-5763-2044] Message not fully read (response) for [14440] handler org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing

/var/log/elasticsearch/elasticsearch.log reporting 
java.lang.IllegalStateException: Message not fully read (request) for requestId [11812], action [internal:discovery/zen/unicast_gte_1_4], readerIndex [59] vs expected [205]; resetting

This comment claims that 4.2 is required
https://discuss.elastic.co/t/upgrade-to-2-0-breaks-kibana-and-logstash/31953/2

**Comment by leifmadsen** [comment]
Note that I built a new role for Kibana 4, using the same method as this one:

https://github.com/leifmadsen/ansible-role-kibana-4

I'm happy to transfer ownership over to @geerlingguy as well. I was going to create a pull request against this repository, but it might be better to separate out kibana 3 vs 4?

**Comment by leifmadsen** [comment]
Here is an example `playbook.yml` I created that uses the other geerlingguy roles to build out a full ELK stack:

```
# main.yml
---
- hosts: elk
  become: yes
  vars_files:
    - vars/main.yml


  roles:
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'geerlingguy.elasticsearch' }
    - { role: 'geerlingguy.logstash' }
    - { role: 'geerlingguy.nginx' }
    - { role: 'leifmadsen.kibana-4' }
```

## Additional files:

**requirements.txt**

```
---
- src: geerlingguy.repo-epel
- src: geerlingguy.elasticsearch
- src: geerlingguy.logstash
- src: geerlingguy.nginx
- src: leifmadsen.kibana-4
```

**Comment by geerlingguy** [comment]
With PR #5, I can confirm that the playbook should get even simpler:

```
---
- hosts: all
  become: yes
  roles:
    - geerlingguy.java
    - geerlingguy.elasticsearch
    - geerlingguy.kibana
```

Note that you need Java 8+ for latest version of Elasticsearch. I'll be working on that role soon, after I finish fixing up this role a bit more.

Also, for now, I'm planning on removing the built-in Nginx configuration, and either moving that proxy/password setup to its own separate role, or recommending people do it on their own outside of this role...
