### ISSUE TITLE
Is this also testing in CentOS?

### ISSUE THREAD

**Issue by thepenguinthatwants** [geerlingguy/ansible-role-kibana#42]
Hi!

I am trying to learn how to write molecule tests and I stumbled upon your blog and it mentioned tests on Ubuntu and CentOS.

I only see
```
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
```
Is it defined some otherways to also test in centos?

Source:
https://www.jeffgeerling.com/blog/2018/testing-your-ansible-roles-molecule
