### ISSUE TITLE
[feature request] install Kibana plugins

### ISSUE THREAD

**Issue by seperman** [geerlingguy/ansible-role-kibana#6]
Feature request:

Install Kibana plugins on demand.

Example:

```
- name: Kibana
  hosts: localhost
  become: true
  roles:
    - kibana
  plugins:
    - sense
```
